import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, Clock3, Database, Play, RefreshCw, Radio, ServerCog, ToggleLeft, ToggleRight, Waves } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { api } from '../api/client'
import type { Discovery, IngestionRequest, Page, Run, Summary, Target } from '../api/types'
import { Empty, Failure, Loading, Pill } from '../components/States'

const tone=(s:string)=>s==='SUCCEEDED'?'good':s==='FAILED'?'bad':s==='RUNNING'?'warn':'neutral' as const
const time=(v:string|null)=>v?new Date(v).toLocaleString():'—'

export default function AdminPage(){
  const [summary,setSummary]=useState<Summary|null>(null),[targets,setTargets]=useState<Target[]>([]),[runs,setRuns]=useState<Run[]>([]),[requests,setRequests]=useState<IngestionRequest[]>([]),[discovery,setDiscovery]=useState<Discovery[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);setError('');try{const [a,b,c,d,e]=await Promise.all([api<Summary>('/api/v1/admin/summary'),api<Page<Target>>('/api/v1/admin/targets?size=50'),api<Page<Run>>('/api/v1/admin/ingestion-runs?size=20'),api<Page<IngestionRequest>>('/api/v1/admin/requests?size=20'),api<Discovery[]>('/api/v1/admin/discovery?status=NEEDS_REVIEW')]);setSummary(a);setTargets(b.content);setRuns(c.content);setRequests(d.content);setDiscovery(e)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setLoading(false)}},[])
  useEffect(()=>{void load();const id=setInterval(()=>void load(true),10000);return()=>clearInterval(id)},[load])
  const action=async(key:string,path:string,init:RequestInit={method:'POST'})=>{setBusy(key);setMessage('');try{await api(path,init);setMessage('Action completed. Operational data refreshed.');await load(true)}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}}
  if(loading)return <div className="mx-auto max-w-[1400px] px-5 py-12"><div className="panel"><Loading label="Reading system state"/></div></div>
  if(error)return <div className="mx-auto max-w-[1000px] px-5 py-12"><div className="panel"><Failure message={error} retry={load}/></div></div>
  const cards=[['Enabled boards',summary?.enabledTargets,ServerCog,'text-pine bg-mint/35'],['Due now',summary?.dueTargets,Clock3,'text-amber-700 bg-amber-50'],['Work in flight',(summary?.pendingIngestionRequests||0)+(summary?.runningIngestionRequests||0),Waves,'text-blue-700 bg-blue-50'],['Failed · 24h',summary?.failedRunsLast24h,AlertTriangle,'text-red-700 bg-red-50'],['Unpublished events',summary?.unpublishedJobEvents,Radio,'text-violet-700 bg-violet-50']] as const
  return <div className="mx-auto max-w-[1440px] px-5 py-10 lg:px-10 lg:py-14"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><p className="eyebrow">Local admin</p><Pill tone="warn">Not authenticated</Pill></div><h1 className="mt-2 font-display text-4xl font-extrabold tracking-[-.05em]">Operations console</h1><p className="mt-3 text-sm text-black/48">Boards, ingestion health, discovery decisions, and publication backlog in one place.</p></div><button className="btn-secondary" onClick={()=>void load()}><RefreshCw size={15}/>Refresh data</button></header>
    {message&&<div className="mt-6 rounded-xl border border-pine/15 bg-mint/20 px-4 py-3 text-sm font-semibold text-pine">{message}</div>}
    <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon,color])=><div key={label} className="panel p-5"><span className={`grid size-9 place-items-center rounded-xl ${color}`}><Icon size={17}/></span><p className="mt-5 font-display text-3xl font-extrabold tracking-tight">{value??'—'}</p><p className="mt-1 text-xs font-bold text-black/40">{label}</p></div>)}</section>
    <div className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1.55fr)_minmax(360px,.8fr)]"><div className="space-y-7"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-black/7 p-5 sm:p-6"><div><p className="eyebrow">Ingestion targets</p><h2 className="mt-1 font-display text-xl font-extrabold">Board schedule</h2></div><Database className="text-black/20"/></div>{targets.length===0?<Empty title="No boards configured" body="Approve a discovered board or create an ingestion target to begin."/>:<div className="divide-y divide-black/7">{targets.map(t=><div key={t.id} className="grid gap-4 p-5 sm:p-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display font-extrabold">{t.company}</h3><Pill>{t.source}</Pill>{t.lastError&&<Pill tone="bad">Latest failure</Pill>}</div><p className="mt-1 text-xs text-black/40">{t.sourceAccount} · every {t.intervalMinutes} min · next {time(t.nextRunAt)}</p>{t.lastError&&<p className="mt-2 line-clamp-2 text-xs text-red-650">{t.lastError}</p>}</div><div className="flex items-center gap-2"><button disabled={busy===t.id} className="btn-secondary" onClick={()=>void action(t.id,`/api/v1/admin/targets/${t.id}`,{method:'PATCH',body:JSON.stringify({enabled:!t.enabled})})}>{t.enabled?<ToggleRight className="text-emerald-600" size={18}/>:<ToggleLeft size={18}/>} {t.enabled?'Enabled':'Disabled'}</button><button disabled={!t.enabled||busy===t.id} className="btn-primary" onClick={()=>void action(t.id,`/api/v1/admin/targets/${t.id}/run`)}><Play size={14}/>Run now</button></div></div>)}</div>}</section>
      <section className="panel overflow-hidden"><div className="border-b border-black/7 p-5 sm:p-6"><p className="eyebrow">Run history</p><h2 className="mt-1 font-display text-xl font-extrabold">Latest ingestion runs</h2></div>{runs.length===0?<Empty title="No ingestion runs" body="Run an enabled board to see timing, counts, and failures here."/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-black/[.025] text-[10px] uppercase tracking-wider text-black/35"><tr><th className="p-4 pl-6">Board</th><th>State</th><th>Started</th><th>Changes</th><th>Error</th><th></th></tr></thead><tbody className="divide-y divide-black/7">{runs.map(r=><tr key={r.id}><td className="p-4 pl-6"><b>{r.sourceAccount}</b><span className="block text-xs text-black/35">{r.source}</span></td><td><Pill tone={tone(r.status)}>{r.status}</Pill></td><td className="text-xs text-black/45">{time(r.startedAt)}</td><td className="text-xs font-bold text-black/50">+{r.created??0} / ~{r.updated??0} / −{r.closed??0}</td><td className="max-w-52 truncate pr-3 text-xs text-red-650" title={r.failureMessage||''}>{r.failureMessage||'—'}</td><td className="pr-5">{r.status==='FAILED'&&<button disabled={busy===r.id} className="btn-secondary" onClick={()=>void action(r.id,`/api/v1/admin/ingestion-runs/${r.id}/retry`)}><RefreshCw size={13}/>Retry</button>}</td></tr>)}</tbody></table></div>}</section></div>
      <aside className="space-y-7"><section className="panel overflow-hidden"><div className="border-b border-black/7 p-5"><p className="eyebrow">Request pipeline</p><h2 className="mt-1 font-display text-lg font-extrabold">Recent work</h2></div>{requests.length===0?<Empty title="Queue is quiet" body="No ingestion requests have been created yet."/>:<div className="divide-y divide-black/7">{requests.slice(0,8).map(r=><div key={r.id} className="flex items-center gap-3 p-4"><span className={`size-2 rounded-full ${r.status==='FAILED'?'bg-red-500':r.status==='RUNNING'?'animate-pulse bg-amber-500':r.status==='SUCCEEDED'?'bg-emerald-500':'bg-blue-500'}`}/><div className="min-w-0 flex-1"><p className="truncate font-mono text-[11px] font-bold">{r.id}</p><p className="mt-0.5 text-[10px] text-black/35">{time(r.createdAt)} · attempt {r.attemptCount}</p></div><Pill tone={tone(r.status)}>{r.status}</Pill></div>)}</div>}</section>
        <section className="panel overflow-hidden"><div className="border-b border-black/7 p-5"><p className="eyebrow">Needs review</p><h2 className="mt-1 font-display text-lg font-extrabold">Discovered boards</h2></div>{discovery.length===0?<Empty title="Review queue is clear" body="Ambiguous discovery results will wait here for an operator decision."/>:<div className="divide-y divide-black/7">{discovery.map(d=><div key={d.id} className="p-5"><h3 className="font-display font-extrabold">{d.companyName}</h3><a href={d.careersUrl} target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-1 truncate text-xs text-pine hover:underline">Careers page<ArrowUpRight size={12}/></a>{d.matchedUrl&&<p className="mt-2 break-all rounded-lg bg-black/4 p-2 font-mono text-[10px] text-black/45">{d.matchedUrl}</p>}<p className="mt-2 text-xs text-black/45">{d.lastError||'Provider/account needs confirmation.'}</p><ApproveForm item={d} busy={busy===d.id} approve={(body)=>action(d.id,`/api/v1/admin/discovery/${d.id}/approve`,{method:'POST',body:JSON.stringify(body)})}/></div>)}</div>}</section>
        <div className="rounded-3xl bg-ink p-6 text-white"><div className="flex items-center gap-2 text-mint"><Activity size={17}/><span className="text-xs font-extrabold uppercase tracking-widest">Event publication</span></div><p className="mt-4 font-display text-3xl font-extrabold">{summary?.unpublishedJobEvents||0}</p><p className="mt-1 text-sm text-white/45">unpublished events waiting for Kafka</p><p className="mt-4 border-t border-white/10 pt-4 text-xs text-white/35">Oldest: {time(summary?.oldestUnpublishedEventAt||null)}. This is outbox backlog, not Kafka consumer lag.</p></div>
      </aside></div>
  </div>
}

function ApproveForm({item,busy,approve}:{item:Discovery;busy:boolean;approve:(body:unknown)=>Promise<void>}){const guessed=item.matchedUrl?.split('/').filter(Boolean).pop()||'';const [account,setAccount]=useState(guessed),[source,setSource]=useState('GREENHOUSE');return <div className="mt-4 grid grid-cols-[1fr_1.3fr] gap-2"><select className="field" value={source} onChange={e=>setSource(e.target.value)}><option>GREENHOUSE</option><option>LEVER</option><option>ASHBY</option></select><input className="field" value={account} onChange={e=>setAccount(e.target.value)} placeholder="Source account"/><button disabled={busy||!account.trim()} onClick={()=>void approve({source,sourceAccount:account})} className="btn-primary col-span-2"><CheckCircle2 size={15}/>Verify & approve</button></div>}
