import { Bell, BellRing, Check, MapPin, Power, PowerOff } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { api } from '../api/client'
import type { Alert, Search } from '../api/types'
import { Empty, Failure, Loading, Pill } from '../components/States'

export default function AlertsPage(){
  const [searches,setSearches]=useState<Search[]|null>(null),[alerts,setAlerts]=useState<Alert[]|null>(null),[error,setError]=useState(''),[unreadOnly,setUnreadOnly]=useState(true)
  const load=useCallback(async()=>{setError('');try{const [s,a]=await Promise.all([api<Search[]>('/api/v1/saved-searches'),api<Alert[]>(`/api/v1/alerts?unread=${unreadOnly}`)]);setSearches(s);setAlerts(a)}catch(e){setError(e instanceof Error?e.message:'Request failed')}},[unreadOnly])
  useEffect(()=>{void load()},[load])
  const toggle=async(s:Search)=>{await api(`/api/v1/saved-searches/${s.id}`,{method:'PATCH',body:JSON.stringify({enabled:!s.enabled})});void load()}
  const read=async(id:string)=>{await api(`/api/v1/alerts/${id}/read`,{method:'PATCH'});void load()}
  return <div className="mx-auto max-w-[1200px] px-5 py-10 lg:px-10 lg:py-14"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Your radar</p><h1 className="mt-2 font-display text-4xl font-extrabold tracking-[-.05em]">Job alerts</h1><p className="mt-3 max-w-xl text-sm leading-6 text-black/50">New opportunities matched against the searches you care about.</p></div><button onClick={()=>setUnreadOnly(!unreadOnly)} className={unreadOnly?'btn-primary':'btn-secondary'}>{unreadOnly?<BellRing size={16}/>:<Bell size={16}/>} {unreadOnly?'Unread only':'Showing all'}</button></header>
    {error?<div className="panel mt-8"><Failure message={error} retry={load}/></div>:!searches||!alerts?<div className="panel mt-8"><Loading label="Loading your alerts"/></div>:<div className="mt-9 grid gap-7 lg:grid-cols-[340px_minmax(0,1fr)]"><aside><h2 className="mb-4 font-display text-lg font-extrabold">Saved searches <span className="text-black/25">{searches.length}</span></h2><div className="space-y-3">{searches.length===0?<div className="panel"><Empty title="No saved searches" body="Build a search on Find jobs, then save it as an alert."/></div>:searches.map(s=><div key={s.id} className={`panel p-5 ${!s.enabled?'opacity-55':''}`}><div className="flex items-start justify-between gap-3"><div><h3 className="font-display font-extrabold">{s.name}</h3><p className="mt-1 text-xs leading-5 text-black/45">{[s.query,s.company,s.location,s.remotePolicy,s.source].filter(Boolean).join(' · ')||'All new jobs'}</p></div><button onClick={()=>void toggle(s)} className={`grid size-9 shrink-0 place-items-center rounded-xl ${s.enabled?'bg-emerald-50 text-emerald-700':'bg-black/5 text-black/35'}`} title={s.enabled?'Disable':'Enable'}>{s.enabled?<Power size={15}/>:<PowerOff size={15}/>}</button></div></div>)}</div></aside>
      <section><h2 className="mb-4 font-display text-lg font-extrabold">Inbox <span className="text-black/25">{alerts.length}</span></h2><div className="panel divide-y divide-black/7 overflow-hidden">{alerts.length===0?<Empty title={unreadOnly?'You’re all caught up':'No alerts yet'} body="When a newly ingested role matches an enabled saved search, it will appear here."/>:alerts.map(a=><article key={a.id} className={`p-5 sm:p-6 ${a.readAt?'bg-black/[.015] opacity-65':'bg-white'}`}><div className="flex items-start gap-4"><span className={`mt-1 size-2 shrink-0 rounded-full ${a.readAt?'bg-black/15':'bg-coral shadow-[0_0_0_5px_rgba(255,121,95,.12)]'}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-display text-lg font-extrabold">{a.job.title}</h3><p className="mt-1 text-sm font-semibold text-black/45">{a.job.company}</p></div><span className="text-xs font-bold text-black/30">{new Date(a.createdAt).toLocaleDateString()}</span></div><p className="mt-3 flex items-center gap-1.5 text-xs text-black/45"><MapPin size={13}/>{a.job.location||'Location flexible'}</p><div className="mt-4 flex flex-wrap items-center gap-2"><Pill>{a.job.remotePolicy}</Pill><a className="btn-secondary ml-auto" href={a.job.applyUrl} target="_blank" rel="noreferrer">View role</a>{!a.readAt&&<button onClick={()=>void read(a.id)} className="btn-primary"><Check size={15}/>Mark read</button>}</div></div></div></article>)}</div></section></div>}
  </div>
}
