import { ArrowLeft, ArrowRight, BookmarkPlus, Building2, ExternalLink, MapPin, Search, SlidersHorizontal, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import type { Job, JobSummary, Page } from '../api/types'
import { Empty, Failure, Loading, Pill } from '../components/States'

const relative = (date:string|null) => date ? new Intl.RelativeTimeFormat('en',{numeric:'auto'}).format(-Math.max(0,Math.round((Date.now()-new Date(date).getTime())/86400000)),'day') : 'Recently'

export default function JobsPage() {
  const [params,setParams]=useSearchParams(), [data,setData]=useState<Page<JobSummary>|null>(null), [error,setError]=useState(''), [loading,setLoading]=useState(true), [selected,setSelected]=useState<Job|null>(null), [detailError,setDetailError]=useState(''), [saveName,setSaveName]=useState(''), [notice,setNotice]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api(`/api/v1/jobs?${params.toString()}`))}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setLoading(false)}},[params])
  useEffect(()=>{void load()},[load])
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const form=new FormData(e.currentTarget), next=new URLSearchParams(); for(const [k,v] of form)if(String(v))next.set(k,String(v)); next.set('page','0');setParams(next)}
  const open=async(id:string)=>{setDetailError('');try{setSelected(await api(`/api/v1/jobs/${id}`))}catch(e){setDetailError(e instanceof Error?e.message:'Could not load job')}}
  const save=async()=>{if(!saveName.trim())return;try{await api('/api/v1/saved-searches',{method:'POST',body:JSON.stringify({name:saveName,...Object.fromEntries(['query','company','source','remotePolicy','location'].map(k=>[k,params.get(k)||null]))})});setSaveName('');setNotice('Search saved — matching jobs will appear in Alerts.')}catch(e){setNotice(e instanceof Error?e.message:'Could not save search')}}
  const page=Number(params.get('page')||0), go=(n:number)=>{const p=new URLSearchParams(params);p.set('page',String(n));setParams(p)}
  return <div className="mx-auto max-w-[1440px] px-5 py-10 lg:px-10 lg:py-14">
    <section className="relative overflow-hidden rounded-[2rem] bg-pine px-6 py-10 text-white lg:px-12 lg:py-14"><div className="absolute -right-24 -top-32 size-96 rounded-full border-[70px] border-mint/10"/><p className="eyebrow !text-mint">Curated from the source</p><h1 className="mt-3 max-w-2xl font-display text-4xl font-extrabold tracking-[-.055em] sm:text-6xl">Find the work that<br/><span className="text-mint">moves you forward.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-white/60 sm:text-base">Search fresh roles across trusted company boards. No reposts, no mystery listings.</p>
      <form onSubmit={submit} className="relative mt-8 grid gap-2 rounded-2xl bg-white p-2 text-ink shadow-2xl lg:grid-cols-[1.4fr_1fr_1fr_auto]">
        <label className="flex items-center gap-2 px-3"><Search size={18} className="text-black/35"/><input name="query" defaultValue={params.get('query')||''} className="h-12 min-w-0 flex-1 text-sm" placeholder="Role, skill, or keyword"/></label>
        <label className="flex items-center gap-2 border-black/8 px-3 lg:border-l"><MapPin size={18} className="text-black/35"/><input name="location" defaultValue={params.get('location')||''} className="h-12 min-w-0 flex-1 text-sm" placeholder="City or region"/></label>
        <label className="flex items-center gap-2 border-black/8 px-3 lg:border-l"><Building2 size={18} className="text-black/35"/><input name="company" defaultValue={params.get('company')||''} className="h-12 min-w-0 flex-1 text-sm" placeholder="Company"/></label>
        <button className="btn h-12 bg-mint px-6 text-pine hover:bg-[#d8ff7d]">Search roles<ArrowRight size={17}/></button>
        <div className="col-span-full flex flex-wrap items-center gap-2 border-t border-black/8 px-2 pt-2"><SlidersHorizontal size={15} className="mx-1 text-black/35"/><select name="source" defaultValue={params.get('source')||''} className="h-9 rounded-lg bg-black/4 px-3 text-xs font-bold"><option value="">All sources</option><option>GREENHOUSE</option><option>LEVER</option><option>ASHBY</option></select><select name="remotePolicy" defaultValue={params.get('remotePolicy')||''} className="h-9 rounded-lg bg-black/4 px-3 text-xs font-bold"><option value="">Any workplace</option><option>REMOTE</option><option>HYBRID</option><option>ONSITE</option><option>UNSPECIFIED</option></select><select name="sort" defaultValue={params.get('sort')||'newest'} className="h-9 rounded-lg bg-black/4 px-3 text-xs font-bold"><option value="newest">Newest first</option><option value="relevance">Most relevant</option></select></div>
      </form>
    </section>
    <div className="mt-9 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
      <section><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Live opportunities</p><h2 className="mt-1 font-display text-2xl font-extrabold tracking-tight">{data?`${data.totalElements.toLocaleString()} roles found`:'Search results'}</h2></div></div>
        <div className="panel divide-y divide-black/7 overflow-hidden">{loading?<Loading label="Scanning job boards"/>:error?<Failure message={error} retry={load}/>:!data?.content.length?<Empty title="No matching roles" body="Try broadening a filter or removing a keyword. Your request succeeded; there just aren’t any matches yet."/>:data.content.map(job=><button key={job.id} onClick={()=>void open(job.id)} className="group flex w-full items-start gap-4 p-5 text-left hover:bg-pine/[.025] sm:p-6"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-pine text-sm font-black text-mint">{job.company.slice(0,2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block font-display text-lg font-extrabold tracking-tight group-hover:text-pine">{job.title}</span><span className="mt-1 block text-sm font-semibold text-black/48">{job.company} <span className="mx-1.5 text-black/15">•</span> {job.location||'Location flexible'}</span><span className="mt-3 flex flex-wrap gap-2"><Pill>{job.remotePolicy}</Pill><Pill>{job.source}</Pill></span></span><span className="shrink-0 text-xs font-bold text-black/35">{relative(job.postedAt||job.firstSeenAt)}</span></button>)}</div>
        {data&&data.totalPages>1&&<div className="mt-5 flex items-center justify-between"><button className="btn-secondary" disabled={page===0} onClick={()=>go(page-1)}><ArrowLeft size={15}/>Previous</button><span className="text-xs font-bold text-black/45">Page {page+1} of {data.totalPages}</span><button className="btn-secondary" disabled={page+1>=data.totalPages} onClick={()=>go(page+1)}>Next<ArrowRight size={15}/></button></div>}
      </section>
      <aside className="space-y-4"><div className="panel p-5"><span className="grid size-10 place-items-center rounded-xl bg-mint/45 text-pine"><BookmarkPlus size={19}/></span><h3 className="mt-4 font-display text-lg font-extrabold">Make this search work for you</h3><p className="mt-2 text-sm leading-6 text-black/45">Save these filters and JobPulse will collect matching new roles.</p><input value={saveName} onChange={e=>setSaveName(e.target.value)} className="field mt-4" placeholder="e.g. Remote backend roles"/><button onClick={()=>void save()} className="btn-primary mt-2 w-full">Save as alert</button>{notice&&<p className="mt-3 text-xs leading-5 text-pine">{notice}</p>}</div><div className="rounded-3xl border border-black/8 p-5"><p className="eyebrow">Source direct</p><p className="mt-2 text-sm leading-6 text-black/50">Every listing links to the company’s own application page, so you know where your application goes.</p></div></aside>
    </div>
    {(selected||detailError)&&<div className="fixed inset-0 z-50 flex justify-end bg-black/35 backdrop-blur-sm" onMouseDown={()=>{setSelected(null);setDetailError('')}}><article onMouseDown={e=>e.stopPropagation()} className="h-full w-full max-w-2xl overflow-y-auto bg-canvas p-6 shadow-2xl sm:p-10"><button className="float-right grid size-10 place-items-center rounded-full bg-black/5" onClick={()=>setSelected(null)}><X size={18}/></button>{detailError?<Failure message={detailError}/>:selected&&<><p className="eyebrow">{selected.company}</p><h2 className="mt-3 pr-12 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{selected.title}</h2><div className="mt-4 flex flex-wrap gap-2"><Pill>{selected.remotePolicy}</Pill><Pill>{selected.source}</Pill>{selected.employmentType&&<Pill>{selected.employmentType}</Pill>}</div><p className="mt-6 flex items-center gap-2 text-sm font-bold text-black/45"><MapPin size={16}/>{selected.location||'Location flexible'}</p><a href={selected.applyUrl} target="_blank" rel="noreferrer" className="btn-primary mt-7">Apply on company site<ExternalLink size={15}/></a><div className="mt-10 border-t border-black/10 pt-8"><p className="eyebrow">About the role</p><div className="mt-4 whitespace-pre-wrap text-[15px] leading-7 text-black/65">{selected.description||'No description was provided by the source.'}</div></div></>}</article></div>}
  </div>
}
